auth-service:
  security:
    secret-key: ${AUTH_SERVICE_SECRET_KEY}
    access-token-expiration: ${AUTH_SERVICE_ACCESS_TOKEN_EXPIRATION:3600000}
    refresh-token-expiration: ${AUTH_SERVICE_REFRESH_TOKEN_EXPIRATION:86400000}
    password-strength: ${AUTH_SERVICE_PASSWORD_STRENGTH:10}
    client-origin: ${AUTH_SERVICE_CLIENT_ORIGIN:http://localhost:3000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.hibernate: warn
    org.springframework.jdbc: warn
    com.azen.authservice: info

server:
  port: ${AUTH_SERVICE_PORT:8081}