spring:
  application:
    name: auth-service

  profiles:
    active: ${AUTH_SERVICE_PROFILE:dev}

  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME:localhost}:${CONFIG_SERVER_PORT:8888}
