services:
# ==================== INFRASTRUCTURE ====================
  postgres-auth-service:
    image: postgres:18
    container_name: postgres-auth-service
    restart: unless-stopped
    env_file:
      - ./.env.docker
    environment:
      POSTGRES_DB: ${AUTH_SERVICE_DB_NAME}
      POSTGRES_USER: ${AUTH_SERVICE_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_SERVICE_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-volume-auth-service:/var/lib/postgresql
    networks:
      - azen-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_SERVICE_DB_USER} -d ${AUTH_SERVICE_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 10

# =================== SERVICES ========================

# ==================== VOLUMES ====================
volumes:
  postgres-volume-auth-service:

# ==================== NETWORKS ====================
networks:
  azen-network:
    driver: bridge